sudo: required

language: generic

branches:
  only:
  - master

services:
  - docker

env:
  - TERRAFORM_VERSION=0.11.4
  - TERRAFORM_VERSION=0.11.7
  - TERRAFORM_VERSION=0.11.10
  - TERRAFORM_VERSION=0.11.11

script:
  - bin/build.sh
  - bin/push.sh
